config/routes.rb
Rails.application.routes.draw do

  get 'search' => 'search#search'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks'}
  resources :questions do
    resources :answers, shallow: true
  end

  namespace :admin do
    # resources :categories
    resources :users
    get "welcome/index" 
    get "console" => "console#index"
    get "user/show"
  end
  
    get "welcome/index"
   resources :profiles
   #resources :users
  # resources :categories
  
  root "welcome#index"
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :answers, dependent: :destroy
	has_many :attachments, dependent: :destroy, as: :attachable
	belongs_to :user
	accepts_nested_attributes_for :attachments
	#is_indexed :fields => ['head', 'body']
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  authorize_resource

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    @question.attachments.build
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  protected
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:head, :body, attachments_attributes: [:file])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :head %><br>
    <%= f.text_field :head %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div>
    <%= f.fields_for :attachments do |a| %>
    <%= a.label :file %><br>
    <%= a.file_field :file %> 
    <% end %> 
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Listing Questions</h1>
<%= link_to 'New Question', new_question_path %>
<br>

<table>
  <thead>
    <tr>
      <th>Head</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.head %></td>
        <td><%= question.body %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
  <strong>Head:</strong>
  <%= @question.head %>
</p>

<p>
  <strong>Body:</strong>
  <%= @question.body %>
</p>

<p>
  <strong>attachments:</strong>
  <ul>
  <% @question.attachments.each do |a| %>
    <li><%= link_to a.file.file.filename, a.file.url %></li>
  <% end %>
  </ul>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>
<br><br>
<h3><strong>Ответы:</strong></h3>
<%= link_to "ответить", new_question_answer_path(@question) %>
<td>
<br><br>
  <strong>
        <% @question.answers.each do |answer| %>
          <p><%= answer.head %></p>
          <p><%= answer.body %></p>
          <p><%= answer.sources %></p>        
          <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
          <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>  
  </strong>
</td>